### ISSUE TITLE
the author of the plugin should be seen under the download button

### ISSUE THREAD

**Issue by RustoMCSpit** [studiorack/studiorack-site#17]
https://studiorack.github.io/studiorack-site/instruments

i feel like listing the author would be useful here

**Comment by kmturley** [comment]
I deliberately chose not to show author, because I don't think that information is useful when making a decision to look at a plugin.
<img width="397" alt="Screenshot 2024-04-27 at 9 50 18 PM" src="https://github.com/studiorack/studiorack-site/assets/1710493/0e691a72-c1cc-4fef-91c7-7788a1482ed8">

Author is displayed on the plugin detail screen when you look for more information
<img width="1226" alt="Screenshot 2024-04-27 at 9 57 00 PM" src="https://github.com/studiorack/studiorack-site/assets/1710493/b717fae8-8911-4fd8-9b43-563aa035c8c5">

So I would say no to this request!
