### ISSUE TITLE
Repo badges

### ISSUE THREAD

**Issue by antonok-edm** [studiorack/studiorack-site#3]
I manually created a [shields.io](https://shields.io) badge for the ampli-Fe repo, but it'd be awesome if you had some kind of official badge for maintainers to use. Even better if it displays the actual version available from https://studiorack.github.io, rather than how it's hardcoded in the image link right now.

For reference - https://github.com/antonok-edm/ampli-Fe/commit/2409349741be40a4e72365e8f6675d447d92dc26.

**Comment by kmturley** [comment]
I think this is an amazing idea, which I had not thought of!

Aren't those kind badges normally used for checking and testing your own builds? Rather than others?

You could definitely have a StudioRack logo, to show featured on. I have some icons already here:
https://github.com/studiorack/studiorack-site/tree/main/public/icons

But would need more thought to how it works.

**Comment by kmturley** [comment]
Created a custom badge which should hopefully look good on GitHub repos:
<img width="144" alt="studiorack-badge" src="https://github.com/studiorack/studiorack-site/assets/1710493/501608ca-0a9c-4050-9201-8a4fc4d01ab8">


Usage is like this:
```
<a href="https://studiorack.github.io/studiorack-site/effects/studiorack/ampli-fe" alt="StudioRack plugin manager" title="Download on StudioRack" target="_blank">
    <img src="https://studiorack.github.io/studiorack-site/icons/studiorack-badge.png" width="144" />
</a>
```
